//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL
    {
        public int id { get; set; }
        public string id_sim { get; set; }
        public Nullable<System.DateTime> time_start { get; set; }
        public Nullable<System.DateTime> time_stop { get; set; }
        public Nullable<int> minute_7hto23h { get; set; }
        public Nullable<int> minute_23hto7h { get; set; }
        public Nullable<int> fare { get; set; }
    
        public virtual SIM SIM { get; set; }
    }
}
